### ISSUE TITLE
**Estudar flask**

### ISSUE THREAD

**Issue by matheusroleal** [karinatronkos/NinaTalks#1]

**Comment by fefeacastro** [comment]
Documentação Flask
https://flask.palletsprojects.com/en/1.1.x/

Introdução 
https://flask.palletsprojects.com/en/1.1.x/quickstart/
https://medium.com/better-programming/building-your-first-website-with-flask-part-1-903a8b44e806

**Comment by alex-abrahao** [comment]
Vídeo tutorial
https://www.youtube.com/watch?v=Z1RJmh_OqeA

**Comment by fefeacastro** [comment]
https://www.youtube.com/watch?v=mqhxxeeTbu0
