### ISSUE TITLE
**Buscar template de parallax**

### ISSUE THREAD

**Issue by matheusroleal** [karinatronkos/NinaTalks#4]

**Comment by matheusroleal** [comment]
Encontrei algumas opções: 

- https://colorlib.com/wp/template/directing

- https://colorlib.com/wp/template/webhostingservice/

- https://colorlib.com/wp/template/jobfinderportal/

- https://colorlib.com/wp/template/seos/

- https://colorlib.com/wp/template/physical-therapy/

Podemos usar um deles como base para o site

**Comment by karinatronkos** [comment]
Gostei muito do webhostingservice e do seos!

**Comment by karinatronkos** [comment]
@matheusroleal vamos de SEOS então, pode ser? ;)

**Comment by matheusroleal** [comment]
Por mim tudo bem :)
